spring:
  application:
    name: hello-server
  datasource:
    url: jdbc:postgresql://localhost:5432/lab_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 127.0.0.1    # Redis地址
      port: 6379         # 默认端口
      database: 0        # 使用0号库

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl